version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build

      - run: sudo npm link

      - run: |
          proxay -m record -h https://www.google.com -t tapes/ &
          # Wait until it loads.
          until (curl http://localhost:3000 2>&1 | grep Google &>/dev/null)
          do
            echo "Waiting until server ready..."
            sleep 5
          done
